### ISSUE TITLE
Yarr addon problem with SSL enabled

### ISSUE THREAD

**Issue by michelebossa** [einschmidt/addon-yarr#82]
Hi,
I'm trying to use the addon but if i use the ssl option the site it is not reachable can you check?

<img width="206" alt="image" src="https://user-images.githubusercontent.com/38975058/151991767-780fad2d-179a-4957-a620-838478136512.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/38975058/151991865-90ff6ab4-0214-473b-a17e-7ff558ddc9a4.png">

into addon log there is no error.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/38975058/151992297-d2153906-c1fa-4159-91c3-742edc651107.png">

if i remove the option i see the webpage.

Thanks.

**Comment by michelebossa** [comment]
yes i have the cert file and i have checked into bash of container and i see my cert file into folder /ssl/

**Comment by einschmidt** [comment]
> i have checked into bash of container and i see my cert file into folder /ssl/

I am a bit uncertain about what that exactly means in your setup. For me, I would put the cert file into the /ssl/ folder in HA, not the addon.

Just searching a bit around, it _could_ be a cert issue.

Have you checked your page via SSL tools, like here?
https://www.ssllabs.com/ssltest/index.html

What's the result?

**Comment by michelebossa** [comment]
I have checked and now the certificated it is TLS 1.3 but the nginx use an old version as 1.2 can you update the file?


<img width="867" alt="image" src="https://user-images.githubusercontent.com/38975058/152010070-9fe05f3f-49cb-4748-a106-1f1a5e7322c0.png">

I have edit into container and now it is ok
<img width="362" alt="image" src="https://user-images.githubusercontent.com/38975058/152010554-67b3b324-5177-439e-8a9e-d21e4a56e915.png">

Thanks.

**Comment by einschmidt** [comment]
That helps a lot, many thanks!

A test build is currently running. And when everything succeeds, an update should become available soon.

I will close this issue for now. Please let me know in case you have any issues with the coming update.

Thanks also for reaching out!

**Comment by michelebossa** [comment]
I have updated and work thanks a lot. I have just a question about ingress i see you have removed the option can i ask why?

**Comment by einschmidt** [comment]
When yarr introduced the user authentication, that login process broke ingress at that time. At that moment, and also due to my personal usage of yarr, it was easier to just disable ingress.
